image:
  file: .gitpod.Dockerfile

tasks:
  - init: python -m pip install --upgrade pip && pip install poetry && poetry export -f requirements.txt --dev --without-hashes --output requirements.txt && pip install -r requirements.txt
    command: pytest
