name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Platform Dependencies
        run: |
          sudo apt install -y xvfb x11-utils herbstluftwm
          sudo apt install -y gcc
          sudo apt install -y libgl1-mesa-glx libqt5x11extras5
          sudo apt install -y libdbus-1-3 libxkbcommon-x11-0 l
          export DISPLAY=:99.0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Tests
        env:
          QT_DEBUG_PLUGINS: 1
        run: xvfb-run poetry run coverage run --source slicereg -m pytest
