name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Install Platform Dependencies
        run: |
          sudo apt install -y xvfb x11-utils libxkbcommon-x11-0  # https://stackoverflow.com/questions/60692711/cant-create-python-qapplication-in-github-action
          Xvfb -ac :99 &
          export DISPLAY=:99.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Tests
        run: xvfb-run --auto-servernum poetry run pytest